# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "my-simon"
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Aaron McGuire"]
  s.date = "2013-02-03"
  s.description = "CLI tool for Simon, the simple PHP project boilerplate!"
  s.email = "aaron.mcguire@evb.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    ".gitignore.orig",
    "DOC/Launch Check List.docx",
    "DOC/Launch Check List.pdf",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.md",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "build/rakefile.rb",
    "config.rb",
    "lib/simon.rb",
    "my-simon.gemspec",
    "scaffolding/simon/controller.tpl",
    "scaffolding/simon/model.tpl",
    "scaffolding/simon/view.tpl",
    "scaffolding/standards/html_template.html",
    "scaffolding/standards/html_template.php",
    "scaffolding/standards/jquery_plugin_template.js",
    "scaffolding/standards/js_template.js",
    "simon",
    "test/helper.rb",
    "test/test_simon.rb",
    "www/.htaccess",
    "www/404.html",
    "www/crossdomain.xml",
    "www/favicon.ico",
    "www/index.php",
    "www/lib/js/homePage.js",
    "www/lib/js/jquery/JQbook.js",
    "www/lib/js/jquery/jquery-1.8.0.min.js",
    "www/lib/js/jquery/jquery.alphanumeric.js",
    "www/lib/js/jquery/jquery.cookie.js",
    "www/lib/js/jquery/jquery.easing.1.3.js",
    "www/lib/js/main.js",
    "www/lib/js/master.js",
    "www/lib/js/plugins/handlebars-1.0.rc.1.js",
    "www/lib/js/plugins/modernizr-1.7.min.js",
    "www/lib/js/plugins/swfobject.js",
    "www/lib/js/plugins_mod/README.txt",
    "www/lib/php/app.php",
    "www/lib/php/controller/index.php",
    "www/lib/php/controller/regex.php",
    "www/lib/php/model/Book.php",
    "www/lib/php/model/Model.php",
    "www/lib/php/plugins/php-activerecord/ActiveRecord.php",
    "www/lib/php/plugins/php-activerecord/lib/CallBack.php",
    "www/lib/php/plugins/php-activerecord/lib/Column.php",
    "www/lib/php/plugins/php-activerecord/lib/Config.php",
    "www/lib/php/plugins/php-activerecord/lib/Connection.php",
    "www/lib/php/plugins/php-activerecord/lib/ConnectionManager.php",
    "www/lib/php/plugins/php-activerecord/lib/DateTime.php",
    "www/lib/php/plugins/php-activerecord/lib/Exceptions.php",
    "www/lib/php/plugins/php-activerecord/lib/Expressions.php",
    "www/lib/php/plugins/php-activerecord/lib/Inflector.php",
    "www/lib/php/plugins/php-activerecord/lib/Model.php",
    "www/lib/php/plugins/php-activerecord/lib/Reflections.php",
    "www/lib/php/plugins/php-activerecord/lib/Relationship.php",
    "www/lib/php/plugins/php-activerecord/lib/SQLBuilder.php",
    "www/lib/php/plugins/php-activerecord/lib/Serialization.php",
    "www/lib/php/plugins/php-activerecord/lib/Singleton.php",
    "www/lib/php/plugins/php-activerecord/lib/Table.php",
    "www/lib/php/plugins/php-activerecord/lib/Utils.php",
    "www/lib/php/plugins/php-activerecord/lib/Validations.php",
    "www/lib/php/plugins/php-activerecord/lib/adapters/MysqlAdapter.php",
    "www/lib/php/plugins/php-activerecord/lib/adapters/OciAdapter.php",
    "www/lib/php/plugins/php-activerecord/lib/adapters/PgsqlAdapter.php",
    "www/lib/php/plugins/php-activerecord/lib/adapters/SqliteAdapter.php",
    "www/lib/php/system/Config.php",
    "www/lib/php/system/config.routes.php",
    "www/lib/php/system/router.php",
    "www/lib/php/template/footer.php",
    "www/lib/php/template/header.php",
    "www/lib/php/view/index.php",
    "www/media/images/facebook_share.jpg",
    "www/robots.txt",
    "www/sandbox/readme.txt",
    "www/sass/javascript.scss",
    "www/sass/layout.scss",
    "www/sass/master.scss",
    "www/sass/reset.scss",
    "www/sass/typography.scss",
    "www/styles/javascript.css",
    "www/styles/layout.css",
    "www/styles/master.css",
    "www/styles/reset.css",
    "www/styles/typography.css"
  ]
  s.homepage = "http://github.com/samcreate/simon"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.23"
  s.summary = "CLI tool for Simon"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<shoulda>, [">= 0"])
      s.add_development_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_development_dependency(%q<bundler>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.8.4"])
      s.add_development_dependency(%q<simplecov>, [">= 0"])
    else
      s.add_dependency(%q<shoulda>, [">= 0"])
      s.add_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_dependency(%q<bundler>, [">= 0"])
      s.add_dependency(%q<jeweler>, ["~> 1.8.4"])
      s.add_dependency(%q<simplecov>, [">= 0"])
    end
  else
    s.add_dependency(%q<shoulda>, [">= 0"])
    s.add_dependency(%q<rdoc>, ["~> 3.12"])
    s.add_dependency(%q<bundler>, [">= 0"])
    s.add_dependency(%q<jeweler>, ["~> 1.8.4"])
    s.add_dependency(%q<simplecov>, [">= 0"])
  end
end

