# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "my-simon"
  s.version = "0.3.10"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Aaron McGuire"]
  s.date = "2014-01-10"
  s.description = "CLI tool for Simon, the simple PHP project boilerplate!"
  s.email = "aaron.mcguire@evb.com"
  s.executables = ["/simon"]
  s.files = [
    ".document",
    ".gitignore",
    ".gitignore.orig",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "bin/simon",
    "lib/simon.rb",
    "my-simon.gemspec",
    "test/helper.rb",
    "test/test_simon.rb"
  ]
  s.homepage = "https://github.com/samcreate/simon-cli"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.25"
  s.summary = "CLI tool for Simon"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

